# Generated by Django 4.2.6 on 2023-12-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='tags',
            new_name='jlpt_level',
        ),
    ]
