# Generated by Django 4.2.6 on 2023-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkanjiprogress',
            old_name='proficiency_level',
            new_name='interval',
        ),
        migrations.AddField(
            model_name='userkanjiprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='userkanjiprogress',
            name='repetition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userkanjiprogress',
            name='last_reviewed',
            field=models.DateField(auto_now=True),
        ),
    ]
