# Generated by Django 4.2.6 on 2023-12-07 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_decks', '0002_rename_proficiency_level_userkanjiprogress_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkanjiprogress',
            name='next_review',
            field=models.DateField(default=datetime.datetime(2023, 12, 7, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
