# Generated by Django 4.2.6 on 2023-10-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.TextField(max_length=10),
        ),
        migrations.DeleteModel(
            name='JLPTLevel',
        ),
    ]
